config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # resources :recipes
  resources :categories, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [ :new, :create ]
  end
  resources :bookmarks, only: [ :destroy ]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

  validates :recipe, presence: true
  validates :category, presence: true
  validates :comments, length: { minimum: 6 }
  validates :recipe_id, uniqueness: { scope: :category_id, message: "This receipt is already bookmarked in this category" }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :categories, through: :bookmarks

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :rating, presence: true, numericality: { greater_than_or_equal_t0: 0, less_than_or_equal_to: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @recipes = Recipe.all
    @bookmark = Bookmark.new
  end

  def create
    @category = Category.find(params[:category_id])
    @recipes = Recipe.all
    # raise
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.category = @category
    # raise
    if @bookmark.save
      redirect_to category_path(@category), notice: 'Recipe was successfully added to the category.'
    else
      # raise @bookmark.errors.full_messages.inspect
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    raise
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@bookmark.category), notice: "Recipe was successfully removed from the category."
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:recipe_id, :comments)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @recipes = @category.recipes
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: "Category was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new.find(params[:id])
    if @recipe.save
      redirect_to @recipe, notice: "Recipe was successfully created."
    else
      render :new
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/bookmarks/new.html.erb
Add recipe to <%= @category.name %>
<%= simple_form_for [@category, @bookmark], local: true do |f| %>
<%= f.input :recipe_id, collection: @recipes, label: "select a Recipe" %>
<%= f.input :comments, label: "comments", placeholder: "Add a comment", input_html: { maxlength: 200 } %>
<%= f.button :submit, "Add Recipe" %>
<% end %>
<%= link_to "Back to Category", category_path(@category) %>

app/views/categories/index.html.erb
All Categories
<ul>
  <% @categories.each do |category| %>
  <li><%= link_to category.name, category_path(category) %></li>
  <% end %>

  <%= link_to "Create New Category", new_category_path %>

app/views/categories/new.html.erb
New Category

<%= simple_form_for @category do |f| %>
<%= f.input :name, label: "Category Name" %>
<%= f.submit "Create Category" %>
<% end %>
<%= link_to "Back to Categories", categories_path %>

app/views/categories/show.html.erb
Category show page
<ul><%= @category.name %>
<% @category.bookmarks.each do |bookmark| %>
<li>
<%= bookmark.recipe.name %>
<%# <% @bookmark = recipe.bookmarks.select { |bookmark| bookmark.category_id == @category.id }  %>

<%= link_to "Delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this recipe from the category?' } %>
</li>
<% end %>
</ul>

<%= link_to "Bookmark Recipe", new_category_bookmark_path(@category) %>
<%= link_to "All categories", categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Cookbook" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# <%= yield :head %>

    <%# <link rel="manifest" href="/manifest.json"> %>
    <%# <link rel="icon" href="/icon.png" type="image/png"> %>
    <%# <link rel="icon" href="/icon.svg" type="image/svg+xml"> %>
    <%# <link rel="apple-touch-icon" href="/icon.png"> %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
Recipes Index

<ul>
<% @recipes.each do |recipe| %>
<li> <%= link_to recipe.name, recipe_path(recipe)%>
<% end %>
</li>
</ul>

app/views/recipes/show.html.erb
Recipe show page
<%= @recipe.name %>
<li><%= @recipe.description %></li>
<%= link_to "Back to all recipes", recipes_path %>